### PR TITLE
Set vcvars for cross-toolchain when targetting arm64

### PR DESCRIPTION
**Pull request by jon-turney**
Required by https://github.com/mesonbuild/meson/pull/6512.

### CODE REVIEW

**Comment by jon-turney** [comment]
Having this install.ps1 script be part of the data bundle seems like a bad idea.

**Comment by mensinda** [comment]
Yeah, this was not my smartest move. At least some parts in it could be moved to the main repo. However, debugging Azure is not fun and I was just happy once I had a good enough solution.

**Comment by jon-turney** [comment]
To make this change available, it seems that a release needs to be made and the tag used bumped in run.ps1?  Can someone make a release, please?

**Comment by mensinda** [comment]
working on it.

**Comment by mensinda** [comment]
[Done](https://github.com/mesonbuild/cidata/releases/tag/ci3)

**Comment by jon-turney** [comment]
Thanks!

**Pull request merged**
